! netops lab 基线配置 — core1（FRR 10.4）
! 接口顺序 = 拓扑链接顺序（eth0 为 clab mgmt）：
!   eth1 -> core2, eth2 -> acc1, eth3 -> acc2
frr version 10.4
frr defaults traditional
hostname core1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 description P2P:core1-core2
 ip address 10.0.12.1/30
 ip ospf network point-to-point
!
interface eth2
 description P2P:core1-acc1
 ip address 10.0.101.1/30
 ip ospf network point-to-point
!
interface eth2.100
 description VLAN100-dot1q-example
 ip address 10.100.0.1/24
!
interface eth3
 description P2P:core1-acc2
 ip address 10.0.102.1/30
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.1
 network 10.0.12.0/30 area 0
 network 10.0.101.0/30 area 0
 network 10.0.102.0/30 area 0
 passive-interface lo
 passive-interface eth2.100
!
line vty
!
end
