! netops lab 基线配置 — acc1（FRR 10.4）
! 接口顺序 = 拓扑链接顺序（eth0 为 clab mgmt）：
!   eth1 -> core1, eth2 -> core2
frr version 10.4
frr defaults traditional
hostname acc1
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.3/32
!
interface eth1
 description P2P:acc1-core1
 ip address 10.0.101.2/30
 ip ospf network point-to-point
!
interface eth1.100
 description VLAN100-dot1q-example
 ip address 10.100.0.2/24
!
interface eth2
 description P2P:acc1-core2
 ip address 10.0.201.2/30
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.3
 network 10.0.101.0/30 area 0
 network 10.0.201.0/30 area 0
 passive-interface lo
 passive-interface eth1.100
!
line vty
!
end
